{{ if .Values.env }}
{{- if .Values.env.secrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "aspnet.fullname" . }}-secrets
  labels:
    {{- include "aspnet.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: {{ include "aspnet.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
    {{- range $key, $value  := .Values.env.secrets }}
    - secretKey: {{ $value }}
      remoteRef:
        key: {{ $key }}
    {{- end }}
  {{- end }}
{{ end  }}
---
{{ if .Values.secretMounts }}
{{- if .Values.secretMounts.secrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "aspnet.fullname" . }}-secrets-mount
  labels:
    {{- include "aspnet.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: {{ include "aspnet.fullname" . }}-secrets-mount
    creationPolicy: Owner
  data:
    # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
    {{- range $key, $value  := .Values.secretMounts.secrets }}
    - secretKey: {{ $value }}
      remoteRef:
        key: {{ $key }}
    {{- end }}
  {{- end }}
  {{ end  }}